version: '3.4'

services:
  customerregistry.api:
    image: ${DOCKER_REGISTRY-}customerregistryapi
    build:
      context: .
      dockerfile: ClientRegistry/Dockerfile
    environment:
         - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=teste;User Id=sa;Password=yourStrong(!)Password;TrustServerCertificate=True
    depends_on: 
         - sqlserver
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    environment:
      MSSQL_SA_PASSWORD: "yourStrong(!)Password"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  redis:
    image: redis:latest
    ports:
    - "6379:6379"